### ISSUE TITLE
Red highlight not showing after writing STOP with autocomplete

### ISSUE THREAD

**Issue by rymawby** [Cwright017/Brightpoint#1]
The red highlight in the gutter is not showing after writing STOP with autocomplete

Steps to reproduce:
- Start typing "ST"
- Autocomplete will pop up
- Hit <enter> on STOP

Expected result: Red highlight is in the gutter

Actual result: No red highlight in the gutter

**Comment by cwright017** [comment]
FIXED as of v0.2.3
